#!/usr/bin/env bash
# Generated by yvc. Secrets are referenced as environment variables,
# never inlined, so this script is safe to commit and can be replayed
# once .env is exported.
set -euo pipefail

# Required: TIKTOK_ACCESS_TOKEN

# [1] query_creator_info
# Mandatory first call: returns the privacy levels this app may use.
curl -X POST 'https://open.tiktokapis.com/v2/post/publish/creator_info/query/' \
  -H 'Authorization: Bearer <TIKTOK_ACCESS_TOKEN>' \
  -H 'Content-Type: application/json'

# [2] init_video_publish
curl -X POST 'https://open.tiktokapis.com/v2/post/publish/video/init/' \
  -H 'Authorization: Bearer <TIKTOK_ACCESS_TOKEN>' \
  -H 'Content-Type: application/json' \
  --data-raw '{"post_info": {"title": "Asgari ücret düşük mü? 30 milyon ücretlinin 18 milyonu asgari ücrete yakın, pay %60'ı geçti. Ama Iğdır'da, Burdur'da durum hiç öyle değil. Sen hangi ş", "privacy_level": "SELF_ONLY", "disable_comment": false, "video_cover_timestamp_ms": 3500}, "source_info": {"source": "FILE_UPLOAD", "video_size": 15034280, "chunk_size": 15034280, "total_chunk_count": 1}}'

# [3] upload_video
curl -X PUT '{upload_url}' \
  -H 'Content-Type: video/mp4' \
  -H 'Content-Range: bytes 0-15034279/15034280' \
  --data-binary @<file>

# [4] fetch_publish_status
curl -X POST 'https://open.tiktokapis.com/v2/post/publish/status/fetch/' \
  -H 'Authorization: Bearer <TIKTOK_ACCESS_TOKEN>' \
  -H 'Content-Type: application/json' \
  --data-raw '{"publish_id": "{publish_id}"}'
