#!/usr/bin/env bash
# Generated by yvc. Secrets are referenced as environment variables,
# never inlined, so this script is safe to commit and can be replayed
# once .env is exported.
set -euo pipefail

# Required: TIKTOK_ACCESS_TOKEN

# [1] query_creator_info
# Mandatory first call: returns the privacy levels this app may use.
curl -X POST 'https://open.tiktokapis.com/v2/post/publish/creator_info/query/' \
  -H 'Authorization: Bearer <TIKTOK_ACCESS_TOKEN>' \
  -H 'Content-Type: application/json'

# [2] init_video_publish
curl -X POST 'https://open.tiktokapis.com/v2/post/publish/video/init/' \
  -H 'Authorization: Bearer <TIKTOK_ACCESS_TOKEN>' \
  -H 'Content-Type: application/json' \
  --data-raw '{"post_info": {"title": "Ücret farkı kapanıyor sanıyordun? Yanılıyorsun, büyüyor. Politikalar üretiliyor ama işe yaramıyor, konu siyasallaşınca kocaman bir kavgaya dönüşüyor. ", "privacy_level": "SELF_ONLY", "disable_comment": false, "video_cover_timestamp_ms": 3500}, "source_info": {"source": "FILE_UPLOAD", "video_size": 18142559, "chunk_size": 18142559, "total_chunk_count": 1}}'

# [3] upload_video
curl -X PUT '{upload_url}' \
  -H 'Content-Type: video/mp4' \
  -H 'Content-Range: bytes 0-18142558/18142559' \
  --data-binary @<file>

# [4] fetch_publish_status
curl -X POST 'https://open.tiktokapis.com/v2/post/publish/status/fetch/' \
  -H 'Authorization: Bearer <TIKTOK_ACCESS_TOKEN>' \
  -H 'Content-Type: application/json' \
  --data-raw '{"publish_id": "{publish_id}"}'
