#!/usr/bin/env bash
# Generated by yvc. Secrets are referenced as environment variables,
# never inlined, so this script is safe to commit and can be replayed
# once .env is exported.
set -euo pipefail

# Required: LINKEDIN_ACCESS_TOKEN, LINKEDIN_ORG_URN

# [1] initialize_upload
# Returns a video URN plus per-part upload instructions.
curl -X POST 'https://api.linkedin.com/rest/videos?action=initializeUpload' \
  -H 'Authorization: Bearer <LINKEDIN_ACCESS_TOKEN>' \
  -H 'LinkedIn-Version: 202506' \
  -H 'X-Restli-Protocol-Version: 2.0.0' \
  -H 'Content-Type: application/json' \
  --data-raw '{"initializeUploadRequest": {"owner": "<LINKEDIN_ORG_URN>", "fileSizeBytes": 38122994, "uploadCaptions": false, "uploadThumbnail": false}}'

# [2] upload_part_1
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[0].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [3] upload_part_2
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[1].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [4] upload_part_3
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[2].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [5] upload_part_4
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[3].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [6] upload_part_5
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[4].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [7] upload_part_6
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[5].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [8] upload_part_7
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[6].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [9] upload_part_8
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[7].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [10] upload_part_9
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[8].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [11] upload_part_10
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[9].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [12] finalize_upload
curl -X POST 'https://api.linkedin.com/rest/videos?action=finalizeUpload' \
  -H 'Authorization: Bearer <LINKEDIN_ACCESS_TOKEN>' \
  -H 'LinkedIn-Version: 202506' \
  -H 'X-Restli-Protocol-Version: 2.0.0' \
  -H 'Content-Type: application/json' \
  --data-raw '{"finalizeUploadRequest": {"video": "{videoUrn}", "uploadToken": "", "uploadedPartIds": ["{etag_1}", "{etag_2}", "{etag_3}", "{etag_4}", "{etag_5}", "{etag_6}", "{etag_7}", "{etag_8}", "{etag_9}", "{etag_10}"]}}'

# [13] create_post
curl -X POST 'https://api.linkedin.com/rest/posts' \
  -H 'Authorization: Bearer <LINKEDIN_ACCESS_TOKEN>' \
  -H 'LinkedIn-Version: 202506' \
  -H 'X-Restli-Protocol-Version: 2.0.0' \
  -H 'Content-Type: application/json' \
  -H 'X-RestLi-Method: CREATE' \
  --data-raw '{"author": "<LINKEDIN_ORG_URN>", "commentary": "In some niche roles, Turkey pays higher salaries than every European country except 2-3.\n\nWage increases made during the cheap-financing era were a good thing — no argument there. But once financing costs spike, sustaining those raises gets a lot harder. As policy rates flow through to borrowing costs, businesses can no longer keep pace with wage growth while balancing cash flow.\n\nThere's also a composition problem: same seniority, same expertise, same role, same company profile — and pay in Turkey still outpaces most of Europe.\n\nDoes this signal a loss of skilled talent, or is it just a politically charged narrative? According to the data, this is measurable: how many people are leaving, is it 1% or 10%, and are they coming back?\n\nHow is your organization managing wage policy under today's financing cost pressure?\n\nhttps://www.datassist.com.tr/?utm_source=linkedin&utm_medium=social_organic&utm_campaign=datassist_clips&utm_content=c05&utm_term=data_number&yvc_v=A&yvc_lang=en\n\n#ücretlendirme #İK #bordro #ücretpolitikası #insankaynakları", "visibility": "PUBLIC", "distribution": {"feedDistribution": "MAIN_FEED", "targetEntities": [], "thirdPartyDistributionChannels": []}, "content": {"media": {"id": "{videoUrn}", "title": ""}}, "lifecycleState": "PUBLISHED", "isReshareDisabledByAuthor": false}'
