#!/usr/bin/env bash
# Generated by yvc. Secrets are referenced as environment variables,
# never inlined, so this script is safe to commit and can be replayed
# once .env is exported.
set -euo pipefail

# Required: YOUTUBE_ACCESS_TOKEN

# [1] init_resumable_upload
# Response Location header carries the resumable session URI.
curl -X POST 'https://www.googleapis.com/upload/youtube/v3/videos' \
  -H 'Authorization: Bearer <YOUTUBE_ACCESS_TOKEN>' \
  -H 'Content-Type: application/json; charset=UTF-8' \
  -H 'X-Upload-Content-Length: 18372495' \
  -H 'X-Upload-Content-Type: video/mp4' \
  --data-raw '{"snippet": {"title": "Gender Pay Gap Kapanmıyor, Büyüyor: İK İçin Ne Anlama Geliyor?", "description": "Gender pay gap azalmıyor, büyüyor. Bu klipte kadın-erkek ücret eşitsizliğinin neden küçülmediğini ve konunun politize olunca neden kemikleşen bir toplumsal tartışmaya dönüştüğünü ele alıyoruz. İK ve bordro ekipleri için veri odaklı bakış. Abone ol, ücret politikası klipleri için takip et.\n\nhttps://www.datassist.com.tr/?utm_source=youtube&utm_medium=social_organic&utm_campaign=datassist_clips&utm_content=c01b&utm_term=data_number&yvc_v=B&yvc_lang=tr", "tags": ["GenderPayGap", "İK", "Bordro", "ÜcretEşitliği"], "categoryId": "22", "defaultLanguage": "tr"}, "status": {"privacyStatus": "private", "selfDeclaredMadeForKids": false, "publishAt": "2026-09-04T14:50:00+00:00"}}'

# [2] upload_bytes
# 8 MB chunks; resume on HTTP 308.
curl -X PUT '{resumable_session_uri}' \
  -H 'Content-Type: video/mp4' \
  -H 'Content-Length: 18372495' \
  --data-binary @<file>
