#!/usr/bin/env bash
# Generated by yvc. Secrets are referenced as environment variables,
# never inlined, so this script is safe to commit and can be replayed
# once .env is exported.
set -euo pipefail

# Required: YOUTUBE_ACCESS_TOKEN

# [1] init_resumable_upload
# Response Location header carries the resumable session URI.
curl -X POST 'https://www.googleapis.com/upload/youtube/v3/videos' \
  -H 'Authorization: Bearer <YOUTUBE_ACCESS_TOKEN>' \
  -H 'Content-Type: application/json; charset=UTF-8' \
  -H 'X-Upload-Content-Length: 15034280' \
  -H 'X-Upload-Content-Type: video/mp4' \
  --data-raw '{"snippet": {"title": "Asgari Ücret Gerçekten Düşük mü? 18 Milyon Çalışanın Verisi", "description": "Asgari ücret Türkiye'de gerçekten düşük mü? Panelde konuşulan veriye göre asgari ücretin toplam ücretler içindeki payı 2011-2014'ten bu yana %60'ların üzerine çıktı; 30 milyon ücretlinin 18 milyonu bu bantta. Ama Iğdır, Burdur, İstanbul ve Ankara arasında tablo aynı değil — şehir bilgisi olmadan yorum yapmak eksik kalıyor. Bordro ve ücret politikası kararları için bölgesel veriye bakın. Datassist'e abone olun, veri odaklı İK içerikleri için takipte kalın.\n\nhttps://www.datassist.com.tr/?utm_source=youtube&utm_medium=social_organic&utm_campaign=datassist_clips&utm_content=c03&utm_term=data_number&yvc_v=A&yvc_lang=tr", "tags": ["AsgariÜcret", "Bordro", "İK", "Datassist"], "categoryId": "22", "defaultLanguage": "tr"}, "status": {"privacyStatus": "private", "selfDeclaredMadeForKids": false, "publishAt": "2026-09-05T14:57:00+00:00"}}'

# [2] upload_bytes
# 8 MB chunks; resume on HTTP 308.
curl -X PUT '{resumable_session_uri}' \
  -H 'Content-Type: video/mp4' \
  -H 'Content-Length: 15034280' \
  --data-binary @<file>
