#!/usr/bin/env bash
# Generated by yvc. Secrets are referenced as environment variables,
# never inlined, so this script is safe to commit and can be replayed
# once .env is exported.
set -euo pipefail

# Required: YOUTUBE_ACCESS_TOKEN

# [1] init_resumable_upload
# Response Location header carries the resumable session URI.
curl -X POST 'https://www.googleapis.com/upload/youtube/v3/videos' \
  -H 'Authorization: Bearer <YOUTUBE_ACCESS_TOKEN>' \
  -H 'Content-Type: application/json; charset=UTF-8' \
  -H 'X-Upload-Content-Length: 18142559' \
  -H 'X-Upload-Content-Type: video/mp4' \
  --data-raw '{"snippet": {"title": "Gender Pay Gap Kapanmıyor, Büyüyor: Ücret Farkı Neden Kemikleşiyor?", "description": "Gender pay gap kapanmıyor, büyüyor. Panelde konuşulan veriye göre kadın-erkek ücret farkı yıllar içinde daralmak yerine genişliyor.\n\nPolitikalar üretilse de konu siyasallaştığında basit bir işyeri meselesi olmaktan çıkıp toplumsal bir kavgaya dönüşüyor ve sorun kemikleşiyor.\n\nBordro ve ücret verisi için abone ol.\n\nhttps://www.datassist.com.tr/?utm_source=youtube&utm_medium=social_organic&utm_campaign=datassist_clips&utm_content=c01a&utm_term=data_number&yvc_v=A&yvc_lang=tr", "tags": ["GenderPayGap", "ÜcretEşitliği", "İK", "Bordro"], "categoryId": "22", "defaultLanguage": "tr"}, "status": {"privacyStatus": "private", "selfDeclaredMadeForKids": false, "publishAt": "2026-09-03T15:07:00+00:00"}}'

# [2] upload_bytes
# 8 MB chunks; resume on HTTP 308.
curl -X PUT '{resumable_session_uri}' \
  -H 'Content-Type: video/mp4' \
  -H 'Content-Length: 18142559' \
  --data-binary @<file>
