#!/usr/bin/env bash
# Generated by yvc. Secrets are referenced as environment variables,
# never inlined, so this script is safe to commit and can be replayed
# once .env is exported.
set -euo pipefail

# Required: LINKEDIN_ACCESS_TOKEN, LINKEDIN_ORG_URN

# [1] initialize_upload
# Returns a video URN plus per-part upload instructions.
curl -X POST 'https://api.linkedin.com/rest/videos?action=initializeUpload' \
  -H 'Authorization: Bearer <LINKEDIN_ACCESS_TOKEN>' \
  -H 'LinkedIn-Version: 202506' \
  -H 'X-Restli-Protocol-Version: 2.0.0' \
  -H 'Content-Type: application/json' \
  --data-raw '{"initializeUploadRequest": {"owner": "<LINKEDIN_ORG_URN>", "fileSizeBytes": 19228624, "uploadCaptions": false, "uploadThumbnail": false}}'

# [2] upload_part_1
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[0].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [3] upload_part_2
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[1].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [4] upload_part_3
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[2].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [5] upload_part_4
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[3].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [6] upload_part_5
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[4].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [7] finalize_upload
curl -X POST 'https://api.linkedin.com/rest/videos?action=finalizeUpload' \
  -H 'Authorization: Bearer <LINKEDIN_ACCESS_TOKEN>' \
  -H 'LinkedIn-Version: 202506' \
  -H 'X-Restli-Protocol-Version: 2.0.0' \
  -H 'Content-Type: application/json' \
  --data-raw '{"finalizeUploadRequest": {"video": "{videoUrn}", "uploadToken": "", "uploadedPartIds": ["{etag_1}", "{etag_2}", "{etag_3}", "{etag_4}", "{etag_5}"]}}'

# [8] create_post
curl -X POST 'https://api.linkedin.com/rest/posts' \
  -H 'Authorization: Bearer <LINKEDIN_ACCESS_TOKEN>' \
  -H 'LinkedIn-Version: 202506' \
  -H 'X-Restli-Protocol-Version: 2.0.0' \
  -H 'Content-Type: application/json' \
  -H 'X-RestLi-Method: CREATE' \
  --data-raw '{"author": "<LINKEDIN_ORG_URN>", "commentary": "The gender pay gap isn't closing. It's widening.\n\nDespite the optimism many HR conversations carry — that pay equity is improving — the data tells a different story. As one expert put it plainly on a recent panel: «unfortunately, the gap is growing.» That's not a policy failure so much as a sign we're intervening in the wrong place.\n\nHere's the trap: when we treat pay inequity as a solved problem and apply surface-level fixes, the underlying issue hardens and resurfaces as something bigger. In the US, for example, once pay equity becomes politicized, it stops being a workplace policy question and turns into a full-blown culture war.\n\nFor payroll and compensation decisions, the starting point can't be good intentions — it has to be measurable data. Otherwise every step we take to 'fix' the gap ends up entrenching it further.\n\nWhat data is driving your organization's pay equity decisions?\n\nhttps://www.datassist.com.tr/?utm_source=linkedin&utm_medium=social_organic&utm_campaign=datassist_clips&utm_content=c04&utm_term=data_number&yvc_v=A&yvc_lang=en\n\n#ÜcretEşitliği #İK #Bordro #GenderPayGap #VeriYönetimi", "visibility": "PUBLIC", "distribution": {"feedDistribution": "MAIN_FEED", "targetEntities": [], "thirdPartyDistributionChannels": []}, "content": {"media": {"id": "{videoUrn}", "title": ""}}, "lifecycleState": "PUBLISHED", "isReshareDisabledByAuthor": false}'
