#!/usr/bin/env bash
# Generated by yvc. Secrets are referenced as environment variables,
# never inlined, so this script is safe to commit and can be replayed
# once .env is exported.
set -euo pipefail

# Required: X_CONSUMER_KEY, X_CONSUMER_SECRET, X_ACCESS_TOKEN, X_ACCESS_SECRET

# [1] media_init
# VERIFY: this account's tier may still use v1.1 media/upload.
curl -X POST 'https://api.x.com/2/media/upload' \
  -H 'Authorization: OAuth oauth_consumer_key="<X_CONSUMER_KEY>", oauth_signature="<HMAC-SHA1>", oauth_version="1.0"'

# [2] media_append_0
curl -X POST 'https://api.x.com/2/media/upload' \
  -H 'Authorization: OAuth oauth_consumer_key="<X_CONSUMER_KEY>", oauth_signature="<HMAC-SHA1>", oauth_version="1.0"'

# [3] media_append_1
curl -X POST 'https://api.x.com/2/media/upload' \
  -H 'Authorization: OAuth oauth_consumer_key="<X_CONSUMER_KEY>", oauth_signature="<HMAC-SHA1>", oauth_version="1.0"'

# [4] media_append_2
curl -X POST 'https://api.x.com/2/media/upload' \
  -H 'Authorization: OAuth oauth_consumer_key="<X_CONSUMER_KEY>", oauth_signature="<HMAC-SHA1>", oauth_version="1.0"'

# [5] media_append_3
curl -X POST 'https://api.x.com/2/media/upload' \
  -H 'Authorization: OAuth oauth_consumer_key="<X_CONSUMER_KEY>", oauth_signature="<HMAC-SHA1>", oauth_version="1.0"'

# [6] media_finalize
# Then poll STATUS until processing_info.state == succeeded.
curl -X POST 'https://api.x.com/2/media/upload' \
  -H 'Authorization: OAuth oauth_consumer_key="<X_CONSUMER_KEY>", oauth_signature="<HMAC-SHA1>", oauth_version="1.0"'

# [7] create_tweet
curl -X POST 'https://api.x.com/2/tweets' \
  -H 'Authorization: OAuth oauth_consumer_key="<X_CONSUMER_KEY>", oauth_signature="<HMAC-SHA1>", oauth_version="1.0"' \
  -H 'Content-Type: application/json' \
  --data-raw '{"text": "Gender pay gap kapanmıyor, büyüyor. Panelde net: «ne yazık ki gap büyüyor.» Sorunu çözülmüş sayıp yüzeysel adım atınca kemikleşiyor, kavgaya dönüşüyor. #ÜcretEşitliği #GenderPayGap\nhttps://www.datassist.com.tr/?utm_source=x&utm_medium=social_organic&utm_campaign=datassist_clips&utm_content=c04&utm_term=data_number&yvc_v=A&yvc_lang=tr", "media": {"media_ids": ["{media_id}"]}}'
