#!/usr/bin/env bash
# Generated by yvc. Secrets are referenced as environment variables,
# never inlined, so this script is safe to commit and can be replayed
# once .env is exported.
set -euo pipefail

# Required: YOUTUBE_ACCESS_TOKEN

# [1] init_resumable_upload
# Response Location header carries the resumable session URI.
curl -X POST 'https://www.googleapis.com/upload/youtube/v3/videos' \
  -H 'Authorization: Bearer <YOUTUBE_ACCESS_TOKEN>' \
  -H 'Content-Type: application/json; charset=UTF-8' \
  -H 'X-Upload-Content-Length: 14925618' \
  -H 'X-Upload-Content-Type: video/mp4' \
  --data-raw '{"snippet": {"title": "Bordroda Şirket Büyüklüğü Ne Zaman Önemsiz Kalır?", "description": "Datassist, bin üzerinde şirkete bordro, ücret ve sosyal güvenlik danışmanlığı veriyor. Global dev şirketlerin Türkiye ekibi 5 kişi olabiliyor, Türkiye'de büyüyüp global'e açılan oyun ve teknoloji şirketleri de var. Bordroda belirleyici olan çalışan sayısı değil, kurumsal olgunluk. Abone ol, Datassist'i takip et.\n\nhttps://www.datassist.com.tr/?utm_source=youtube&utm_medium=social_organic&utm_campaign=datassist_clips&utm_content=c02&utm_term=question&yvc_v=A&yvc_lang=tr", "tags": ["bordro", "İK", "datassist", "kurumsallaşma"], "categoryId": "22", "defaultLanguage": "tr"}, "status": {"privacyStatus": "private", "selfDeclaredMadeForKids": false, "publishAt": "2026-09-02T15:05:00+00:00"}}'

# [2] upload_bytes
# 8 MB chunks; resume on HTTP 308.
curl -X PUT '{resumable_session_uri}' \
  -H 'Content-Type: video/mp4' \
  -H 'Content-Length: 14925618' \
  --data-binary @<file>
