#!/usr/bin/env bash
# Generated by yvc. Secrets are referenced as environment variables,
# never inlined, so this script is safe to commit and can be replayed
# once .env is exported.
set -euo pipefail

# Required: LINKEDIN_ACCESS_TOKEN, LINKEDIN_ORG_URN

# [1] initialize_upload
# Returns a video URN plus per-part upload instructions.
curl -X POST 'https://api.linkedin.com/rest/videos?action=initializeUpload' \
  -H 'Authorization: Bearer <LINKEDIN_ACCESS_TOKEN>' \
  -H 'LinkedIn-Version: 202506' \
  -H 'X-Restli-Protocol-Version: 2.0.0' \
  -H 'Content-Type: application/json' \
  --data-raw '{"initializeUploadRequest": {"owner": "<LINKEDIN_ORG_URN>", "fileSizeBytes": 19228624, "uploadCaptions": false, "uploadThumbnail": false}}'

# [2] upload_part_1
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[0].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [3] upload_part_2
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[1].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [4] upload_part_3
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[2].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [5] upload_part_4
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[3].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [6] upload_part_5
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[4].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [7] finalize_upload
curl -X POST 'https://api.linkedin.com/rest/videos?action=finalizeUpload' \
  -H 'Authorization: Bearer <LINKEDIN_ACCESS_TOKEN>' \
  -H 'LinkedIn-Version: 202506' \
  -H 'X-Restli-Protocol-Version: 2.0.0' \
  -H 'Content-Type: application/json' \
  --data-raw '{"finalizeUploadRequest": {"video": "{videoUrn}", "uploadToken": "", "uploadedPartIds": ["{etag_1}", "{etag_2}", "{etag_3}", "{etag_4}", "{etag_5}"]}}'

# [8] create_post
curl -X POST 'https://api.linkedin.com/rest/posts' \
  -H 'Authorization: Bearer <LINKEDIN_ACCESS_TOKEN>' \
  -H 'LinkedIn-Version: 202506' \
  -H 'X-Restli-Protocol-Version: 2.0.0' \
  -H 'Content-Type: application/json' \
  -H 'X-RestLi-Method: CREATE' \
  --data-raw '{"author": "<LINKEDIN_ORG_URN>", "commentary": "Gender pay gap kapanmıyor, büyüyor.\n\nTürkiye'de İK gündeminde sık duyduğumuz «kadın-erkek ücret eşitliği iyileşiyor» iyimserliğinin aksine, panelde vurgulanan veri tam tersini söylüyor: «Hocam ne yazık ki gap büyüyor.» Bu, politika üretiminde bir başarısızlık değil, yanlış yerden müdahale ettiğimizin işareti.\n\nSorun şu: eşitsizliği çözülmüş varsayıp yüzeysel adımlar atınca, asıl mesele kemikleşiyor ve yeni, daha büyük tartışmalara dönüşüyor. ABD örneğinde olduğu gibi konu politize olduğunda, basit bir işyeri düzenlemesi olmaktan çıkıp toplumsal bir kavgaya dönüşebiliyor.\n\nBordro ve ücret politikalarını kurarken çıkış noktamız iyi niyet değil, ölçülebilir veri olmalı. Aksi halde attığımız her adım, çözdüğümüzü sandığımız problemi büyütüyor.\n\nSizin kurumunuzda ücret eşitliği kararları hangi veriye dayanıyor?\n\nhttps://www.datassist.com.tr/?utm_source=linkedin&utm_medium=social_organic&utm_campaign=datassist_clips&utm_content=c04&utm_term=data_number&yvc_v=A&yvc_lang=tr\n\n#ÜcretEşitliği #İK #Bordro #GenderPayGap #VeriYönetimi", "visibility": "PUBLIC", "distribution": {"feedDistribution": "MAIN_FEED", "targetEntities": [], "thirdPartyDistributionChannels": []}, "content": {"media": {"id": "{videoUrn}", "title": ""}}, "lifecycleState": "PUBLISHED", "isReshareDisabledByAuthor": false}'
