#!/usr/bin/env bash
# Generated by yvc. Secrets are referenced as environment variables,
# never inlined, so this script is safe to commit and can be replayed
# once .env is exported.
set -euo pipefail

# Required: LINKEDIN_ACCESS_TOKEN, LINKEDIN_ORG_URN

# [1] initialize_upload
# Returns a video URN plus per-part upload instructions.
curl -X POST 'https://api.linkedin.com/rest/videos?action=initializeUpload' \
  -H 'Authorization: Bearer <LINKEDIN_ACCESS_TOKEN>' \
  -H 'LinkedIn-Version: 202506' \
  -H 'X-Restli-Protocol-Version: 2.0.0' \
  -H 'Content-Type: application/json' \
  --data-raw '{"initializeUploadRequest": {"owner": "<LINKEDIN_ORG_URN>", "fileSizeBytes": 38122994, "uploadCaptions": false, "uploadThumbnail": false}}'

# [2] upload_part_1
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[0].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [3] upload_part_2
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[1].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [4] upload_part_3
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[2].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [5] upload_part_4
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[3].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [6] upload_part_5
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[4].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [7] upload_part_6
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[5].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [8] upload_part_7
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[6].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [9] upload_part_8
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[7].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [10] upload_part_9
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[8].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [11] upload_part_10
# Collect the ETag from each part; finalize needs them in order.
curl -X PUT '{uploadInstructions[9].uploadUrl}' \
  -H 'Content-Type: application/octet-stream' \
  --data-binary @<file>

# [12] finalize_upload
curl -X POST 'https://api.linkedin.com/rest/videos?action=finalizeUpload' \
  -H 'Authorization: Bearer <LINKEDIN_ACCESS_TOKEN>' \
  -H 'LinkedIn-Version: 202506' \
  -H 'X-Restli-Protocol-Version: 2.0.0' \
  -H 'Content-Type: application/json' \
  --data-raw '{"finalizeUploadRequest": {"video": "{videoUrn}", "uploadToken": "", "uploadedPartIds": ["{etag_1}", "{etag_2}", "{etag_3}", "{etag_4}", "{etag_5}", "{etag_6}", "{etag_7}", "{etag_8}", "{etag_9}", "{etag_10}"]}}'

# [13] create_post
curl -X POST 'https://api.linkedin.com/rest/posts' \
  -H 'Authorization: Bearer <LINKEDIN_ACCESS_TOKEN>' \
  -H 'LinkedIn-Version: 202506' \
  -H 'X-Restli-Protocol-Version: 2.0.0' \
  -H 'Content-Type: application/json' \
  -H 'X-RestLi-Method: CREATE' \
  --data-raw '{"author": "<LINKEDIN_ORG_URN>", "commentary": "Türkiye'de bazı niş pozisyonlarda ücretler, Avrupa'nın 2-3 ülkesi dışında hepsinden yüksek.\n\nUcuz finansman döneminde yapılan ücret artışları güzel bir gelişme, itirazımız yok. Ama finansman maliyeti bu kadar pahalılaşınca aynı artışları sürdürmek artık mümkün değil. Politika faizi borçlanma maliyetine yansıdıkça, işletmelerin cash flow'unu dengelemek için o artış hızını koruyamadığı bir tabloyla karşı karşıyayız.\n\nDiğer yanda kompozisyon problemi var: aynı seniorite, aynı bilgi, aynı pozisyon, aynı şirket profiliyle Türkiye'de Avrupa'nın büyük çoğunluğundan daha yüksek ücret alınan sektörler mevcut.\n\nPeki bu durum nitelikli iş gücü kaybını mı tetikliyor, yoksa siyasi gündemin ürettiği bir algı mı? Konuşmacıya göre bu data'dan okunabilir bir soru: kaç kişi gidiyor, %1 mi %10 mu, ve gidenler geri dönüyor mu?\n\nSiz bordro ve ücret politikalarınızda bu finansman maliyeti baskısını nasıl yönetiyorsunuz?\n\nhttps://www.datassist.com.tr/?utm_source=linkedin&utm_medium=social_organic&utm_campaign=datassist_clips&utm_content=c05&utm_term=data_number&yvc_v=A&yvc_lang=tr\n\n#ücretlendirme #İK #bordro #ücretpolitikası #insankaynakları", "visibility": "PUBLIC", "distribution": {"feedDistribution": "MAIN_FEED", "targetEntities": [], "thirdPartyDistributionChannels": []}, "content": {"media": {"id": "{videoUrn}", "title": ""}}, "lifecycleState": "PUBLISHED", "isReshareDisabledByAuthor": false}'
