#!/usr/bin/env bash
# Generated by yvc. Secrets are referenced as environment variables,
# never inlined, so this script is safe to commit and can be replayed
# once .env is exported.
set -euo pipefail

# Required: IG_USER_ID, IG_ACCESS_TOKEN

# [1] check_publishing_limit
# 50 published posts per rolling 24h; check headroom before posting.
curl -X GET 'https://graph.facebook.com/v21.0/<IG_USER_ID>/content_publishing_limit' \
  -H 'Authorization: Bearer <IG_ACCESS_TOKEN>'

# [2] create_container
# Asynchronous: returns a creation_id that must be polled.
curl -X POST 'https://graph.facebook.com/v21.0/<IG_USER_ID>/media' \
  -H 'Authorization: Bearer <IG_ACCESS_TOKEN>'

# [3] poll_container_status
# Poll every 5s until FINISHED, cap at 5 minutes.
curl -X GET 'https://graph.facebook.com/v21.0/{creation_id}' \
  -H 'Authorization: Bearer <IG_ACCESS_TOKEN>'

# [4] publish_container
curl -X POST 'https://graph.facebook.com/v21.0/<IG_USER_ID>/media_publish' \
  -H 'Authorization: Bearer <IG_ACCESS_TOKEN>'
